name: team_aid
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  animate_do: ^3.0.2
  animated_custom_dropdown: ^1.5.0
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.6
  go_router: ^7.0.1
  google_fonts: ^4.0.4
  hooks_riverpod: ^2.3.6
  http: ^0.13.6
  iconsax: ^0.0.8
  responsive_sizer: ^3.1.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/login/