name: team_aid
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  animate_do: ^3.0.2
  animated_custom_dropdown: ^1.5.0
  dartz: ^0.10.1
  dropdown_search: ^5.0.6
  expandable: ^5.0.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_hooks: ^0.18.6
  flutter_phone_direct_caller: ^2.1.1
  flutter_secure_storage: ^8.0.0
  go_router: ^7.0.1
  google_fonts: ^4.0.4
  hooks_riverpod: ^2.3.6
  http: ^0.13.6
  iconsax: ^0.0.8
  responsive_sizer: ^3.1.1
  searchable_listview: ^2.4.0
  shared_preferences: ^2.1.1

dev_dependencies:
  custom_lint:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  riverpod_lint: ^1.3.2
  very_good_analysis: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - .env.staging
    - assets/
    - assets/login/
